"""patch(0.0.1): add article status

Revision ID: e7c4cb7f7748
Revises: ed44bb17ba4a
Create Date: 2026-06-30 17:34:23.923150
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7c4cb7f7748'
down_revision: str | None = 'ed44bb17ba4a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('status', sa.String(length=20), nullable=True))
    # 数据迁移: 回填存量行 status 为 'draft'
    op.execute("UPDATE articles SET status = 'draft' WHERE status IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'status')
    # ### end Alembic commands ###
