"""alpha(0.0.7): add metadata jsonb

Revision ID: 2cbfc65ead84
Revises: 4eecb03a1096
Create Date: 2026-07-01 10:24:38.301114
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2cbfc65ead84'
down_revision: str | None = '4eecb03a1096'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'metadata')
    # ### end Alembic commands ###
